- hosts: localhost

  tasks:

    - include_tasks:
        file: roles/start_metricbeat/tasks/main.yml
      tags:
        #тут наш тэг для остановки
        - start metricbeat

    - include_tasks:
        file: roles/stop_metricbeat/tasks/main.yml
      tags:
        #тут наш тэг для запуска
        - stop metricbeat