- hosts: localhost

  tasks:

    - include_role:
        name: start_metricbeat
        apply:
          tags: start metricbeat
      tags:
        #тут наш тэг для остановки
        - start metricbeat

    - include_role:
        name: stop_metricbeat
        apply:
          tags: stop metricbeat
      tags:
        #тут наш тэг для запуска
        - stop metricbeat