- hosts: localhost

  tasks:

    - name: Stop metricbeat
      debug:
        msg: Stop metricbeat
      tags:
        #тут наш тэг для остановки
        - stop metricbeat

    - name: Start metricbeat
      debug:
        msg: Start metricbeat
      tags:
        #тут наш тэг для запуска
        - start metricbeat